### PR TITLE
Add support for more `\begin` blocks

### PR DESCRIPTION
**Pull request by skalnik**
One can make LaTeX math with `\begin{math}` and `\begin{displaymath}` as well as the currently supported `\begin{equation}`. This adds support for the other mentioned `\begin` styles.

### CODE REVIEW

**Comment by gjtorikian** [comment]
I like this. 

I'm having a hell of a time figuring out why the build fails on 2.1, though: https://travis-ci.org/gjtorikian/math-to-itex/jobs/149882679

It passes on 2.0.

**Comment by gjtorikian** [comment]
@skalnik Mind merging in `master`? I made some changes to the Travis setup to fix it. I hope.

**Comment by gjtorikian** [comment]
Cool. It's out as 0.4.0 now.

**Comment by skalnik** [comment]
> Cool. It's out as 0.4.0 now.

❤️ Thanks!

**Pull request merged**
